import { FollowUp, FollowUpColumn } from "../types/followUpTypes";
import { mockQueries } from "@/data/queryData";

// Enhanced follow-ups with proper enquiry and booking integration
export const mockFollowUps: FollowUp[] = [
  {
    id: "fu-001",
    title: "Call client about Dubai package",
    description: "Need to discuss the hotel options in Dubai package",
    dueDate: "2025-05-20T10:00:00.000Z",
    priority: "high",
    status: "pending",
    category: "enquiry",
    type: "client-call",
    queryId: "TQ-2024-003",
    agentId: "AG-101",
    agentName: "Alex Johnson",
    assignedTo: "Mike Marketing",
    createdAt: "2025-05-12T09:00:00.000Z",
    updatedAt: "2025-05-12T09:00:00.000Z",
    tags: ["client-call", "dubai"],
    enquiryDetails: {
      enquiryId: "TQ-2024-003",
      destination: "UAE - Dubai, Abu Dhabi",
      travelDates: {
        from: "2024-02-28",
        to: "2024-03-08"
      },
      paxCount: 5,
      packageType: "family",
      enquiryStatus: "proposal-sent",
      priority: "normal",
      assignedTo: "Mike Marketing",
      budget: {
        min: 3500,
        max: 5000,
        currency: "USD"
      }
    },
    contactMethod: "phone",
    isAutoGenerated: false
  },
  {
    id: "fu-002",
    title: "Send visa requirements for Thailand",
    description: "Email visa checklist to client for upcoming Thailand trip",
    dueDate: "2025-05-16T14:00:00.000Z",
    priority: "medium",
    status: "in-progress",
    category: "documentation",
    type: "document-collection",
    queryId: "ENQ20250001",
    agentId: "AG-102",
    agentName: "Sarah Wilson",
    assignedTo: "Sarah Sales",
    createdAt: "2025-05-11T11:30:00.000Z",
    updatedAt: "2025-05-13T10:15:00.000Z",
    tags: ["visa", "thailand"],
    enquiryDetails: {
      enquiryId: "ENQ20250001",
      destination: "Thailand - Bangkok, Ayutthaya",
      travelDates: {
        from: "2025-02-14",
        to: "2025-02-19"
      },
      paxCount: 2,
      packageType: "cultural",
      enquiryStatus: "new",
      priority: "normal"
    },
    contactMethod: "email",
    reminderSent: true,
    lastContactDate: "2025-05-13T10:15:00.000Z"
  },
  {
    id: "fu-003",
    title: "Confirm hotel booking in Paris",
    description: "Call Hotel de Paris to confirm reservation #12345",
    dueDate: "2025-05-15T12:00:00.000Z",
    priority: "high",
    status: "pending",
    category: "booking",
    type: "vendor-confirmation",
    queryId: "TQ-2024-004",
    agentId: "AG-103",
    agentName: "Michael Brown",
    assignedTo: "Sarah Sales",
    createdAt: "2025-05-10T15:45:00.000Z",
    updatedAt: "2025-05-10T15:45:00.000Z",
    tags: ["hotel", "paris"],
    bookingDetails: {
      bookingId: "BK-2024-004",
      bookingStatus: "confirmed",
      bookingReference: "HTL-PAR-12345",
      totalAmount: 12500,
      paidAmount: 5000,
      balanceAmount: 7500,
      paymentDueDate: "2025-05-10T00:00:00.000Z",
      travelStartDate: "2024-05-15",
      travelEndDate: "2024-05-22",
      vendorConfirmations: {
        hotels: false,
        flights: true,
        transfers: true,
        activities: true
      }
    },
    contactMethod: "phone"
  },
  {
    id: "fu-004",
    title: "Update client on flight status",
    description: "Inform client about flight schedule change",
    dueDate: "2025-05-14T09:30:00.000Z",
    priority: "urgent",
    status: "completed",
    category: "travel",
    type: "travel-support",
    queryId: "TQ-2024-004",
    agentId: "AG-104",
    agentName: "Emma Davis",
    assignedTo: "Sarah Sales",
    createdAt: "2025-05-09T13:20:00.000Z",
    updatedAt: "2025-05-13T16:40:00.000Z",
    completedAt: "2025-05-13T16:40:00.000Z",
    tags: ["flight", "schedule-change"],
    enquiryDetails: {
      enquiryId: "TQ-2024-004",
      destination: "Maldives - Male, Hulhumale",
      travelDates: {
        from: "2024-05-15",
        to: "2024-05-22"
      },
      paxCount: 2,
      packageType: "luxury",
      enquiryStatus: "confirmed",
      priority: "high",
      assignedTo: "Sarah Sales"
    },
    contactMethod: "phone",
    outcome: "Client informed and satisfied with new flight timings",
    notes: "Client was understanding about the change"
  },
  {
    id: "fu-005",
    title: "Collect outstanding payment",
    description: "Remind client about pending payment for Bali package",
    dueDate: "2025-05-18T11:00:00.000Z",
    priority: "high",
    status: "pending",
    category: "payment",
    type: "payment-reminder",
    queryId: "TQ-2024-006",
    agentId: "AG-105",
    agentName: "David Clark",
    assignedTo: "Operations Staff",
    createdAt: "2025-05-12T10:10:00.000Z",
    updatedAt: "2025-05-12T10:10:00.000Z",
    tags: ["payment", "bali"],
    bookingDetails: {
      bookingId: "BK-2024-006",
      bookingStatus: "confirmed",
      totalAmount: 3200,
      paidAmount: 1600,
      balanceAmount: 1600,
      paymentDueDate: "2025-05-18T00:00:00.000Z"
    },
    contactMethod: "email",
    isAutoGenerated: true
  },
  {
    id: "fu-006",
    title: "Send itinerary document",
    description: "Email final itinerary to client for upcoming trip",
    dueDate: "2025-05-17T13:45:00.000Z",
    priority: "medium",
    status: "pending",
    category: "documentation",
    type: "itinerary-delivery",
    queryId: "TQ-2024-007",
    agentId: "AG-106",
    agentName: "Olivia Smith",
    assignedTo: "Sarah Sales",
    createdAt: "2025-05-11T14:30:00.000Z",
    updatedAt: "2025-05-11T14:30:00.000Z",
    tags: ["itinerary", "document"],
    bookingDetails: {
      bookingStatus: "confirmed",
      travelStartDate: "2024-06-01",
      travelEndDate: "2024-06-12"
    },
    contactMethod: "email"
  },
  {
    id: "fu-007",
    title: "Check availability for boat tour",
    description: "Verify availability for sunset boat tour in Santorini",
    dueDate: "2025-05-16T10:30:00.000Z",
    priority: "medium",
    status: "in-progress",
    category: "booking",
    type: "vendor-confirmation",
    queryId: "ENQ20250003",
    agentId: "AG-107",
    agentName: "James Wilson",
    assignedTo: "Mike Marketing",
    createdAt: "2025-05-10T09:15:00.000Z",
    updatedAt: "2025-05-12T11:20:00.000Z",
    tags: ["tour", "santorini"],
    enquiryDetails: {
      enquiryId: "ENQ20250003",
      destination: "Thailand - Koh Samui, Bangkok",
      travelDates: {
        from: "2025-04-20",
        to: "2025-04-28"
      },
      paxCount: 2,
      packageType: "luxury",
      enquiryStatus: "in-progress",
      priority: "urgent",
      assignedTo: "Mike Marketing"
    },
    contactMethod: "phone"
  },
  {
    id: "fu-008",
    title: "Arrange airport transfer",
    description: "Book airport pickup for client arriving at JFK",
    dueDate: "2025-05-19T16:00:00.000Z",
    priority: "high",
    status: "pending",
    category: "booking",
    type: "booking-confirmation",
    queryId: "TQ-2024-002",
    agentId: "AG-108",
    agentName: "Sophia Miller",
    assignedTo: "Sarah Sales",
    createdAt: "2025-05-13T08:45:00.000Z",
    updatedAt: "2025-05-13T08:45:00.000Z",
    tags: ["transfer", "airport"],
    bookingDetails: {
      bookingStatus: "pending",
      vendorConfirmations: {
        hotels: true,
        flights: true,
        transfers: false,
        activities: true
      }
    },
    contactMethod: "phone"
  },
  {
    id: "fu-009",
    title: "Post-travel feedback collection",
    description: "Call client to collect feedback about recent Rome trip",
    dueDate: "2025-05-15T15:30:00.000Z",
    priority: "low",
    status: "completed",
    category: "post-travel",
    type: "post-travel-feedback",
    queryId: "TQ-2024-001",
    agentId: "AG-109",
    agentName: "William Taylor",
    assignedTo: "Sarah Sales",
    createdAt: "2025-05-08T12:50:00.000Z",
    updatedAt: "2025-05-13T14:30:00.000Z",
    completedAt: "2025-05-13T14:30:00.000Z",
    tags: ["feedback", "post-travel"],
    bookingDetails: {
      bookingStatus: "completed"
    },
    contactMethod: "phone",
    outcome: "Excellent feedback received, client very satisfied",
    notes: "Client recommended to friends, potential referral"
  },
  {
    id: "fu-010",
    title: "Follow up on visa application",
    description: "Check status of client's visa application for Japan",
    dueDate: "2025-05-17T09:00:00.000Z",
    priority: "urgent",
    status: "in-progress",
    category: "documentation",
    type: "visa-follow",
    queryId: "TQ-2024-002",
    agentId: "AG-110",
    agentName: "Isabella Moore",
    assignedTo: "Sarah Sales",
    createdAt: "2025-05-11T16:20:00.000Z",
    updatedAt: "2025-05-13T10:05:00.000Z",
    tags: ["visa", "japan"],
    enquiryDetails: {
      enquiryId: "TQ-2024-002",
      destination: "Japan - Tokyo, Kyoto, Osaka",
      travelDates: {
        from: "2024-04-10",
        to: "2024-04-20"
      },
      paxCount: 4,
      packageType: "business",
      enquiryStatus: "in-progress",
      priority: "medium",
      assignedTo: "Sarah Sales"
    },
    contactMethod: "email",
    reminderSent: true,
    recurringSchedule: {
      frequency: "weekly",
      interval: 1,
      endDate: "2025-06-01T00:00:00.000Z"
    }
  }
];

export const getInitialColumns = (): FollowUpColumn[] => {
  return [
    {
      id: 'pending',
      title: 'To Do',
      followUps: mockFollowUps.filter(task => task.status === 'pending')
    },
    {
      id: 'in-progress',
      title: 'In Progress',
      followUps: mockFollowUps.filter(task => task.status === 'in-progress')
    },
    {
      id: 'completed',
      title: 'Completed',
      followUps: mockFollowUps.filter(task => task.status === 'completed')
    }
  ];
};

// Enhanced utility functions for enquiry integration
export const getFollowUpsByEnquiryId = (enquiryId: string): FollowUp[] => {
  return mockFollowUps.filter(followUp => followUp.queryId === enquiryId);
};

export const getFollowUpsByCategory = (category: string): FollowUp[] => {
  return mockFollowUps.filter(followUp => followUp.category === category);
};

export const getOverdueFollowUps = (): FollowUp[] => {
  const now = new Date();
  return mockFollowUps.filter(followUp => 
    new Date(followUp.dueDate) < now && 
    followUp.status !== 'completed' && 
    followUp.status !== 'cancelled'
  );
};

export const getFollowUpsByAssignee = (assignedTo: string): FollowUp[] => {
  return mockFollowUps.filter(followUp => followUp.assignedTo === assignedTo);
};

export const getFollowUpStats = () => {
  const total = mockFollowUps.length;
  const pending = mockFollowUps.filter(f => f.status === 'pending').length;
  const inProgress = mockFollowUps.filter(f => f.status === 'in-progress').length;
  const completed = mockFollowUps.filter(f => f.status === 'completed').length;
  const overdue = getOverdueFollowUps().length;
  const urgent = mockFollowUps.filter(f => f.priority === 'urgent').length;

  return {
    total,
    pending,
    inProgress,
    completed,
    overdue,
    urgent
  };
};