
export type FollowUpPriority = 'low' | 'medium' | 'high' | 'urgent';
export type FollowUpStatus = 'pending' | 'in-progress' | 'completed' | 'cancelled' | 'overdue' | 'scheduled';
export type FollowUpCategory = 'general' | 'enquiry' | 'booking' | 'payment' | 'documentation' | 'travel' | 'post-travel';
export type FollowUpType = 
  | 'client-call' | 'client-email' | 'proposal-follow' | 'payment-reminder' 
  | 'booking-confirmation' | 'document-collection' | 'pre-travel-check' 
  | 'travel-support' | 'post-travel-feedback' | 'visa-follow' | 'vendor-confirmation'
  | 'itinerary-delivery' | 'emergency-contact' | 'review-request';

export interface EnquiryDetails {
  enquiryId: string;
  destination: string;
  travelDates: {
    from: string;
    to: string;
  };
  paxCount: number;
  packageType: string;
  enquiryStatus: string;
  priority: string;
  assignedTo?: string;
  budget?: {
    min: number;
    max: number;
    currency: string;
  };
}

export interface BookingDetails {
  bookingId?: string;
  bookingStatus?: 'confirmed' | 'pending' | 'cancelled' | 'completed';
  bookingReference?: string;
  totalAmount?: number;
  paidAmount?: number;
  balanceAmount?: number;
  paymentDueDate?: string;
  travelStartDate?: string;
  travelEndDate?: string;
  vendorConfirmations?: {
    hotels: boolean;
    flights: boolean;
    transfers: boolean;
    activities: boolean;
  };
}

export interface FollowUp {
  id: string;
  title: string;
  description?: string;
  dueDate: string;
  priority: FollowUpPriority;
  status: FollowUpStatus;
  category: FollowUpCategory;
  type: FollowUpType;
  queryId?: string;
  agentId?: string;
  agentName?: string;
  assignedTo?: string;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
  tags?: string[];
  
  // Enhanced enquiry and booking integration
  enquiryDetails?: EnquiryDetails;
  bookingDetails?: BookingDetails;
  
  // Follow-up specific fields
  reminderSent?: boolean;
  lastContactDate?: string;
  nextContactDate?: string;
  contactMethod?: 'phone' | 'email' | 'whatsapp' | 'sms';
  outcome?: string;
  notes?: string;
  
  // Automation fields
  isAutoGenerated?: boolean;
  parentFollowUpId?: string;
  recurringSchedule?: {
    frequency: 'daily' | 'weekly' | 'monthly';
    interval: number;
    endDate?: string;
  };
}

export interface FollowUpColumn {
  id: string;
  title: string;
  followUps: FollowUp[];
}
