

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useParams, useNavigate } from 'react-router-dom';
import { useToast } from '@/hooks/use-toast';
import { useAutoSave } from '@/hooks/useAutoSave';
import { Query } from '@/types/query';
import { ItineraryDay } from '@/components/proposal/DayByDayItineraryBuilder';
import { useProposalBuilder } from '@/hooks/useProposalBuilder';
import EnhancedProposalService from '@/services/enhancedProposalService';
import ProposalService from '@/services/proposalService';
import { 
  Save, Clock, Wifi, WifiOff, AlertCircle, 
  ArrowLeft, Plus, Calendar, DollarSign,
  CheckCircle, RefreshCw, ChefHat, Utensils
} from 'lucide-react';

interface EnhancedDayWiseBuilderProps {
  queryId?: string;
  proposalId?: string;
}

const EnhancedDayWiseBuilder: React.FC<EnhancedDayWiseBuilderProps> = ({
  queryId: propQueryId,
  proposalId
}) => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { toast } = useToast();
  
  const currentQueryId = propQueryId || id;
  const [query, setQuery] = useState<Query | null>(null);
  const [loading, setLoading] = useState(true);
  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
  const [draftLoaded, setDraftLoaded] = useState(false);

  const {
    days,
    totalCost,
    addDay,
    updateDay,
    removeDay,
    autoGenerateDaysFromQuery,
    saveDraft,
    generateProposal
  } = useProposalBuilder(currentQueryId);

  // Auto-save setup
  const autoSaveKey = proposalId ? `proposal_${proposalId}` : `draft_${currentQueryId}`;
  const {
    lastSaved,
    isOnline,
    isSaving,
    manualSave,
    restoreData,
    clearAutoSave
  } = useAutoSave({
    key: autoSaveKey,
    data: { days, totalCost, queryId: currentQueryId, proposalId },
    interval: 30000, // 30 seconds
    onSave: async (data) => {
      await saveDraft();
      setHasUnsavedChanges(false);
    },
    onRestore: (data) => {
      console.log('Restored auto-saved data:', data);
      setDraftLoaded(true);
    }
  });

  useEffect(() => {
    const loadData = async () => {
      try {
        if (!currentQueryId) {
          throw new Error('Query ID not provided');
        }

        console.log('Loading query data for:', currentQueryId);
        const queryData = await ProposalService.getQueryByIdAsync(currentQueryId);
        if (!queryData) {
          throw new Error(`Query ${currentQueryId} not found`);
        }

        setQuery(queryData);
        console.log('Query loaded successfully:', queryData);

        // Check if we have existing draft data
        const existingDraft = localStorage.getItem(`proposal_draft_${currentQueryId}`);
        if (existingDraft) {
          try {
            const parsed = JSON.parse(existingDraft);
            console.log('Found existing draft:', parsed);
            
            if (parsed.days && parsed.days.length > 0) {
              setDraftLoaded(true);
              toast({
                title: "Draft loaded",
                description: `Found saved draft with ${parsed.days.length} days. Continue editing where you left off.`
              });
            }
          } catch (error) {
            console.error('Error parsing existing draft:', error);
            localStorage.removeItem(`proposal_draft_${currentQueryId}`);
          }
        }

        // Check for auto-saved data
        const restoredData = restoreData();
        if (restoredData && restoredData.days?.length > 0) {
          toast({
            title: "Auto-saved work restored",
            description: `Your previous work has been restored from auto-save (${restoredData.days.length} days)`
          });
        }
        
        // If no saved data and days are empty, generate initial days
        if (!existingDraft && !restoredData && days.length === 0) {
          console.log('No existing draft found, generating initial days');
          autoGenerateDaysFromQuery(queryData);
        }
      } catch (error) {
        console.error('Error loading data:', error);
        toast({
          title: "Error loading data",
          description: error instanceof Error ? error.message : "Failed to load query",
          variant: "destructive"
        });
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, [currentQueryId, days.length, restoreData, autoGenerateDaysFromQuery]);

  // Track changes
  useEffect(() => {
    if (days.length > 0 && !loading) {
      setHasUnsavedChanges(true);
    }
  }, [days, totalCost, loading]);

  const enhanceWithCulinaryActivities = () => {
    if (!query) return;
    
    const createActivity = (name: string, description: string, cost: number, type: 'sightseeing' | 'activity' | 'meal' = 'activity') => ({
      id: `activity_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      name,
      description,
      duration: '2-3 hours',
      cost,
      type,
      startTime: '09:00',
      endTime: '12:00'
    });

    const culinaryActivities = {
      bangkok: [
        createActivity("Street Food Tour in Chinatown", "Explore authentic street food with local guide", 80, 'activity'),
        createActivity("Thai Cooking Class", "Learn to cook traditional Thai dishes", 120, 'activity'),
        createActivity("Chatuchak Weekend Market Visit", "Explore the famous weekend market food stalls", 50, 'sightseeing'),
        createActivity("Floating Market Tour", "Visit Damnoen Saduak floating market", 90, 'sightseeing'),
        createActivity("Bangkok Food Walk", "Evening food walk through local neighborhoods", 70, 'activity'),
        createActivity("Rooftop Restaurant Dinner", "Fine dining with city views", 150, 'meal'),
        createActivity("Local Market Breakfast", "Traditional breakfast at local market", 30, 'meal')
      ],
      chiangmai: [
        createActivity("Northern Thai Cooking Class", "Learn Khao Soi and other northern specialties", 100, 'activity'),
        createActivity("Sunday Walking Street Food Tour", "Explore Chang Khlan Road food stalls", 60, 'activity'),
        createActivity("Local Market Visit", "Visit Warorot Market with food tastings", 45, 'sightseeing'),
        createActivity("Organic Farm Visit", "Visit organic farm with cooking experience", 110, 'activity'),
        createActivity("Traditional Lanna Dinner", "Authentic northern Thai dinner experience", 85, 'meal'),
        createActivity("Coffee Plantation Tour", "Visit local coffee farms in the mountains", 95, 'sightseeing')
      ]
    };

    const updatedDays = days.map((day) => {
      const cityKey = day.city.toLowerCase().replace(' ', '') as keyof typeof culinaryActivities;
      const availableActivities = culinaryActivities[cityKey] || culinaryActivities.bangkok;
      
      let newActivities = [...day.activities];
      let additionalCost = 0;
      
      // Add activities based on day number and city
      if (day.dayNumber === 1) {
        // Arrival day - light activity
        const activity = availableActivities[6] || availableActivities[0]; // Local market breakfast
        newActivities.push(activity);
        additionalCost += activity.cost;
      } else if (day.dayNumber === 2) {
        // First full day - cooking class and market
        const activities = cityKey === 'bangkok' ? [availableActivities[1], availableActivities[2]] : [availableActivities[0], availableActivities[2]];
        newActivities.push(...activities);
        additionalCost += activities.reduce((sum, act) => sum + act.cost, 0);
      } else if (day.dayNumber === 3) {
        // Street food tour
        const activity = availableActivities[0]; // Street food tour
        newActivities.push(activity);
        additionalCost += activity.cost;
      } else if (day.dayNumber === 4) {
        // Market visit and special dining
        const activities = cityKey === 'bangkok' ? [availableActivities[3], availableActivities[5]] : [availableActivities[3], availableActivities[4]];
        newActivities.push(...activities);
        additionalCost += activities.reduce((sum, act) => sum + act.cost, 0);
      } else if (day.dayNumber === 5) {
        // Food walk and local experience
        const activity = cityKey === 'bangkok' ? availableActivities[4] : availableActivities[1];
        newActivities.push(activity);
        additionalCost += activity.cost;
      } else if (day.dayNumber === 6) {
        // Cultural food experience
        const activity = cityKey === 'bangkok' ? availableActivities[1] : availableActivities[5];
        newActivities.push(activity);
        additionalCost += activity.cost;
      } else if (day.dayNumber === 7) {
        // Final experience before departure
        const activity = cityKey === 'bangkok' ? availableActivities[2] : availableActivities[4];
        newActivities.push(activity);
        additionalCost += activity.cost;
      }
      
      return {
        ...day,
        activities: newActivities,
        totalCost: day.totalCost + additionalCost,
        description: day.description.includes('Food') ? day.description : `${day.description} Featuring authentic Thai culinary experiences.`
      };
    });

    // Update each day
    updatedDays.forEach(day => {
      updateDay(day.id, day);
    });

    toast({
      title: "Culinary activities added!",
      description: `Enhanced ${days.length} days with cooking classes, street food tours, and market visits.`,
      duration: 4000
    });
  };

  const handleSaveProposal = async () => {
    try {
      if (!query) return;

      console.log('Saving proposal with days:', days);
      
      let finalProposalId = proposalId;
      
      if (!finalProposalId) {
        // Create new proposal
        finalProposalId = EnhancedProposalService.createProposal(query.id, {
          query,
          modules: days.map(day => ({
            id: day.id,
            type: 'sightseeing' as const,
            name: day.title,
            category: 'daily-itinerary',
            data: day,
            pricing: {
              basePrice: day.totalCost,
              finalPrice: day.totalCost,
              currency: 'USD'
            },
            status: 'active' as const,
            metadata: {
              supplier: 'Internal',
              confirmationRequired: false,
              tags: ['day-by-day', day.city.toLowerCase()]
            }
          })),
          totals: {
            subtotal: totalCost,
            discountAmount: 0,
            total: totalCost,
            moduleCount: days.length
          }
        });
      }

      // Save the itinerary data
      await generateProposal();
      clearAutoSave();
      setHasUnsavedChanges(false);

      toast({
        title: "Proposal saved",
        description: `Proposal ${finalProposalId} saved successfully with ${days.length} days`
      });

      // Navigate to proposal view
      navigate(`/proposals/${finalProposalId}`);
    } catch (error) {
      console.error('Error saving proposal:', error);
      toast({
        title: "Save failed",
        description: "Failed to save proposal. Please try again.",
        variant: "destructive"
      });
    }
  };

  const handleRefreshDraft = async () => {
    try {
      if (!currentQueryId) return;
      
      const existingDraft = localStorage.getItem(`proposal_draft_${currentQueryId}`);
      if (existingDraft) {
        const parsed = JSON.parse(existingDraft);
        if (parsed.days && parsed.days.length > 0) {
          // Force reload by clearing and re-setting
          window.location.reload();
        }
      }
    } catch (error) {
      console.error('Error refreshing draft:', error);
    }
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
    }).format(amount);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center space-y-4">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <h2 className="text-xl font-semibold">Loading Day-wise Builder...</h2>
          <p className="text-sm text-muted-foreground">Checking for saved drafts...</p>
        </div>
      </div>
    );
  }

  if (!query) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Card className="w-full max-w-md">
          <CardHeader>
            <CardTitle className="text-center text-red-600">Query Not Found</CardTitle>
          </CardHeader>
          <CardContent className="text-center space-y-4">
            <p>The requested query could not be found.</p>
            <Button onClick={() => navigate('/queries')} className="w-full">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Queries
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50">
      <div className="max-w-7xl mx-auto p-6 space-y-6">
        {/* Header with Auto-save Status */}
        <Card className="bg-gradient-to-r from-blue-600 to-purple-600 text-white border-none">
          <CardHeader>
            <div className="flex justify-between items-start">
              <div>
                <CardTitle className="text-2xl mb-2">
                  Enhanced Day-wise Proposal Builder
                </CardTitle>
                <p className="text-blue-100">
                  {query.destination.cities.join(', ')}, {query.destination.country}
                </p>
                <p className="text-sm text-blue-100 mt-1">
                  Query ID: {query.id} • {days.length} days planned
                </p>
              </div>
              <div className="flex flex-col items-end gap-2">
                <div className="flex items-center gap-2">
                  {isOnline ? (
                    <Wifi className="h-4 w-4 text-green-300" />
                  ) : (
                    <WifiOff className="h-4 w-4 text-red-300" />
                  )}
                  <span className="text-sm">
                    {isOnline ? 'Online' : 'Offline'}
                  </span>
                </div>
                {draftLoaded && (
                  <div className="flex items-center gap-2 text-sm text-green-100">
                    <CheckCircle className="h-3 w-3" />
                    Draft loaded
                  </div>
                )}
                {lastSaved && (
                  <div className="flex items-center gap-2 text-sm text-blue-100">
                    <Clock className="h-3 w-3" />
                    Auto-saved: {lastSaved.toLocaleTimeString()}
                  </div>
                )}
                {isSaving && (
                  <div className="flex items-center gap-2 text-sm text-blue-100">
                    <div className="animate-spin rounded-full h-3 w-3 border border-white border-t-transparent"></div>
                    Saving...
                  </div>
                )}
              </div>
            </div>
          </CardHeader>
        </Card>

        {/* Auto-save and Connection Status */}
        {(hasUnsavedChanges || !isOnline || draftLoaded) && (
          <Card className="border-orange-200 bg-orange-50">
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 text-orange-800">
                  <AlertCircle className="h-4 w-4" />
                  {!isOnline ? (
                    <span>You're offline. Changes are being saved locally and will sync when online.</span>
                  ) : draftLoaded ? (
                    <span>Draft data loaded successfully. Continue editing where you left off.</span>
                  ) : hasUnsavedChanges ? (
                    <span>You have unsaved changes. Auto-save is active every 30 seconds.</span>
                  ) : null}
                </div>
                {draftLoaded && (
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleRefreshDraft}
                    className="gap-2"
                  >
                    <RefreshCw className="h-3 w-3" />
                    Refresh Draft
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <Card>
            <CardContent className="p-4 text-center">
              <Calendar className="h-8 w-8 mx-auto mb-2 text-blue-500" />
              <div className="text-2xl font-bold">{days.length}</div>
              <div className="text-sm text-muted-foreground">Days Planned</div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4 text-center">
              <DollarSign className="h-8 w-8 mx-auto mb-2 text-green-500" />
              <div className="text-2xl font-bold">{formatCurrency(totalCost)}</div>
              <div className="text-sm text-muted-foreground">Total Cost</div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4 text-center">
              <div className="text-2xl font-bold">{query.paxDetails.adults + query.paxDetails.children + query.paxDetails.infants}</div>
              <div className="text-sm text-muted-foreground">Travelers</div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4 text-center">
              <div className="text-2xl font-bold">{formatCurrency(totalCost / Math.max(1, query.paxDetails.adults + query.paxDetails.children + query.paxDetails.infants))}</div>
              <div className="text-sm text-muted-foreground">Per Person</div>
            </CardContent>
          </Card>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-4 justify-between items-center">
          <div className="flex gap-2">
            <Button onClick={addDay} variant="outline" className="gap-2">
              <Plus className="h-4 w-4" />
              Add Day
            </Button>
            <Button onClick={manualSave} variant="outline" className="gap-2" disabled={isSaving}>
              <Save className="h-4 w-4" />
              {isSaving ? 'Saving...' : 'Save Draft'}
            </Button>
          </div>
          <div className="flex gap-2">
            <Button onClick={() => navigate('/queries')} variant="outline" className="gap-2">
              <ArrowLeft className="h-4 w-4" />
              Back to Queries
            </Button>
            <Button 
              onClick={enhanceWithCulinaryActivities} 
              variant="outline" 
              className="gap-2 border-orange-200 text-orange-700 hover:bg-orange-50"
              disabled={days.length === 0}
            >
              <ChefHat className="h-4 w-4" />
              Add Culinary Activities
            </Button>
            <Button onClick={handleSaveProposal} className="gap-2" disabled={days.length === 0}>
              <Save className="h-4 w-4" />
              Save as Proposal
            </Button>
          </div>
        </div>

        {/* Day-wise Itinerary Content */}
        <div className="space-y-4">
          {days.length === 0 ? (
            <Card>
              <CardContent className="p-8 text-center">
                <Calendar className="h-12 w-12 mx-auto mb-4 opacity-50" />
                <p className="text-lg font-medium mb-2">No days planned yet</p>
                <p className="text-sm text-muted-foreground mb-4">
                  Start building your day-wise itinerary or load from a saved draft
                </p>
                <Button onClick={addDay} className="gap-2">
                  <Plus className="h-4 w-4" />
                  Add First Day
                </Button>
              </CardContent>
            </Card>
          ) : (
            days.map((day) => (
              <Card key={day.id} className="border-l-4 border-l-blue-500">
                <CardHeader>
                  <div className="flex justify-between items-start">
                    <div>
                      <CardTitle className="flex items-center gap-2">
                        <Badge variant="outline">Day {day.dayNumber}</Badge>
                        {day.title}
                      </CardTitle>
                      <p className="text-sm text-muted-foreground mt-1">
                        {day.city} • {new Date(day.date).toLocaleDateString()}
                      </p>
                    </div>
                    <div className="text-right">
                      <p className="text-lg font-bold">{formatCurrency(day.totalCost)}</p>
                      <p className="text-sm text-muted-foreground">Day Total</p>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <p className="text-sm">{day.description}</p>
                    
                    {/* Activities */}
                    {day.activities.length > 0 && (
                      <div>
                        <h4 className="font-medium mb-2">Activities</h4>
                        <div className="space-y-2">
                          {day.activities.map((activity, index) => (
                            <div key={index} className="flex justify-between items-center p-2 bg-gray-50 rounded">
                              <div>
                                <p className="font-medium text-sm">{activity.name}</p>
                                <p className="text-xs text-muted-foreground">{activity.description}</p>
                              </div>
                              <p className="font-medium text-sm">{formatCurrency(activity.cost)}</p>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Meals */}
                    <div className="flex gap-2">
                      {day.meals.breakfast && <Badge variant="secondary" className="text-xs">Breakfast</Badge>}
                      {day.meals.lunch && <Badge variant="secondary" className="text-xs">Lunch</Badge>}
                      {day.meals.dinner && <Badge variant="secondary" className="text-xs">Dinner</Badge>}
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </div>
      </div>
    </div>
  );
};

export default EnhancedDayWiseBuilder;
