import { useState, useEffect, useCallback } from 'react';
import { ItineraryDay } from '@/components/proposal/DayByDayItineraryBuilder';
import ProposalService from '@/services/proposalService';
import { Query } from '@/types/query';
import { calculateTripDuration } from '@/utils/currencyUtils';
import { saveAccommodationData, loadAccommodationData, AccommodationOption } from '@/utils/accommodationUtils';

interface UseProposalBuilderOptions {
  draftType?: 'daywise' | 'enhanced';
  autoLoadDraft?: boolean;
  initialTab?: string;
}

interface UseProposalBuilderReturn {
  days: ItineraryDay[];
  totalCost: number;
  loading: boolean;
  selectedDayId: string | null;
  setSelectedDayId: (dayId: string | null) => void;
  addDay: () => void;
  addMultipleDays: (count: number) => void;
  updateDay: (dayId: string, updates: Partial<ItineraryDay>) => void;
  removeDay: (dayId: string) => void;
  reorderDay: (dayId: string, direction: 'up' | 'down') => void;
  autoGenerateDaysFromQuery: (query: Query) => void;
  generateDaysFromCityAllocations: (query: Query, allocations: any[]) => void;
  addHotelToDay: (dayId: string, hotel: any, price?: number) => void;
  addTransportToDay: (dayId: string, transport: any, price?: number) => void;
  addSightseeingToDay: (dayId: string, activity: any, price?: number) => void;
  saveDraft: (draftType?: string) => Promise<string>;
  generateProposal: () => Promise<string>;
  saveAccommodations: (accommodations: AccommodationOption[]) => void;
  loadSpecificDraft: (draftId: string, draftType: string) => Promise<void>;
}

export const useProposalBuilder = (queryId?: string, options?: UseProposalBuilderOptions): UseProposalBuilderReturn => {
  const [days, setDays] = useState<ItineraryDay[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedDayId, setSelectedDayId] = useState<string | null>(null);
  
  const draftType = options?.draftType || 'daywise';

  // Enhanced draft loading with type support
  const loadDraftData = useCallback((specificDraftType?: string) => {
    if (!queryId) return false;
    
    const targetDraftType = specificDraftType || draftType;
    console.log('Loading draft data for query:', queryId, 'type:', targetDraftType);
    
    // Try different storage keys based on draft type
    const storageKeys = [
      `proposal_draft_${queryId}_${targetDraftType}`,
      `proposal_draft_${queryId}`,
      `enhanced_proposal_${queryId}`,
      `proposal_persistence_${queryId}`
    ];
    
    for (const key of storageKeys) {
      const savedDraft = localStorage.getItem(key);
      if (savedDraft) {
        try {
          const parsedDraft = JSON.parse(savedDraft);
          console.log('Parsed draft data from', key, ':', parsedDraft);
          
          // Handle different draft formats
          let daysData = parsedDraft.days || parsedDraft.itineraryData || [];
          
          if (Array.isArray(daysData)) {
            const validatedDays = daysData.map((day: any, index: number) => {
              const validDay: ItineraryDay = {
                id: day.id || `day_${Date.now()}_${index}`,
                dayNumber: day.dayNumber || (index + 1),
                title: day.title || `Day ${index + 1}`,
                city: day.city || '',
                description: day.description || '',
                date: day.date || new Date().toISOString().split('T')[0],
                activities: Array.isArray(day.activities) ? day.activities : [],
                transport: Array.isArray(day.transport) ? day.transport : [],
                accommodations: Array.isArray(day.accommodations) ? day.accommodations : [],
                accommodation: day.accommodation || undefined,
                meals: day.meals || {
                  breakfast: false,
                  lunch: false,
                  dinner: false
                },
                totalCost: typeof day.totalCost === 'number' ? day.totalCost : 0
              };
              
              return validDay;
            });
            
            console.log('Validated days from', key, ':', validatedDays);
            setDays(validatedDays);
            return true;
          }
        } catch (error) {
          console.error('Error loading saved draft from', key, ':', error);
          localStorage.removeItem(key);
        }
      }
    }
    
    return false;
  }, [queryId, draftType]);

  // Load specific draft by ID and type
  const loadSpecificDraft = useCallback(async (draftId: string, draftType: string) => {
    console.log('Loading specific draft:', draftId, 'type:', draftType);
    
    const storageKey = `proposal_draft_${draftId}_${draftType}`;
    const savedDraft = localStorage.getItem(storageKey);
    
    if (!savedDraft) {
      throw new Error(`Draft not found: ${draftId}`);
    }
    
    try {
      const parsedDraft = JSON.parse(savedDraft);
      const daysData = parsedDraft.days || parsedDraft.itineraryData || [];
      
      if (Array.isArray(daysData)) {
        const validatedDays = daysData.map((day: any, index: number) => ({
          id: day.id || `day_${Date.now()}_${index}`,
          dayNumber: day.dayNumber || (index + 1),
          title: day.title || `Day ${index + 1}`,
          city: day.city || '',
          description: day.description || '',
          date: day.date || new Date().toISOString().split('T')[0],
          activities: Array.isArray(day.activities) ? day.activities : [],
          transport: Array.isArray(day.transport) ? day.transport : [],
          accommodations: Array.isArray(day.accommodations) ? day.accommodations : [],
          accommodation: day.accommodation || undefined,
          meals: day.meals || {
            breakfast: false,
            lunch: false,
            dinner: false
          },
          totalCost: typeof day.totalCost === 'number' ? day.totalCost : 0
        }));
        
        setDays(validatedDays);
        console.log('Loaded specific draft successfully');
      }
    } catch (error) {
      console.error('Error parsing specific draft:', error);
      throw new Error('Invalid draft format');
    }
  }, []);

  // Enhanced draft loading with URL parameter support
  useEffect(() => {
    if (queryId) {
      // Check URL parameters for specific loading instructions
      const urlParams = new URLSearchParams(window.location.search);
      const shouldAutoLoad = options?.autoLoadDraft || urlParams.get('loadDraft') === 'true';
      const specificDraftType = urlParams.get('draftType') || draftType;
      const draftId = urlParams.get('draftId') || queryId;
      
      if (shouldAutoLoad) {
        console.log('Loading draft with parameters:', { queryId, draftId, specificDraftType });
        
        // Try to load specific draft first
        if (draftId !== queryId) {
          loadSpecificDraft(draftId, specificDraftType).catch(() => {
            // Fallback to regular draft loading
            const draftLoaded = loadDraftData(specificDraftType);
            if (draftLoaded) {
              console.log('Fallback draft data loaded successfully');
            } else {
              console.log('No valid draft found');
            }
          });
        } else {
          const draftLoaded = loadDraftData(specificDraftType);
          if (draftLoaded) {
            console.log('Draft data loaded successfully');
          } else {
            console.log('No valid draft found');
          }
        }
      }
    }
  }, [queryId, loadDraftData, loadSpecificDraft, options?.autoLoadDraft, draftType]);

  // Calculate total cost
  const totalCost = days.reduce((sum, day) => sum + day.totalCost, 0);

  const addDay = useCallback(() => {
    const newDay: ItineraryDay = {
      id: `day_${Date.now()}`,
      dayNumber: days.length + 1,
      title: `Day ${days.length + 1}`,
      city: '',
      description: '',
      date: new Date().toISOString().split('T')[0],
      activities: [],
      transport: [],
      accommodations: [],
      meals: {
        breakfast: false,
        lunch: false,
        dinner: false
      },
      totalCost: 0
    };

    setDays(prev => [...prev, newDay]);
    // No auto-save when adding empty day
  }, [days.length]);

  const addMultipleDays = useCallback((count: number) => {
    const newDays: ItineraryDay[] = [];
    for (let i = 0; i < count; i++) {
      const dayNumber = days.length + i + 1;
      const newDay: ItineraryDay = {
        id: `day_${Date.now()}_${i}`,
        dayNumber,
        title: `Day ${dayNumber}`,
        city: '',
        description: '',
        date: new Date().toISOString().split('T')[0],
        activities: [],
        transport: [],
        accommodations: [],
        meals: {
          breakfast: false,
          lunch: false,
          dinner: false
        },
        totalCost: 0
      };
      newDays.push(newDay);
    }
    setDays(prev => [...prev, ...newDays]);
    // No auto-save when adding empty days
  }, [days.length]);

  const autoGenerateDaysFromQuery = useCallback((query: Query) => {
    const tripDuration = calculateTripDuration(query.travelDates.from, query.travelDates.to);
    if (!tripDuration) return;

    const startDate = new Date(query.travelDates.from);
    const generatedDays: ItineraryDay[] = [];

    for (let i = 0; i < tripDuration.days; i++) {
      const currentDate = new Date(startDate);
      currentDate.setDate(startDate.getDate() + i);
      
      const isFirstDay = i === 0;
      const isLastDay = i === tripDuration.days - 1;
      
      let title = `Day ${i + 1}`;
      let description = '';
      let defaultCity = query.destination.cities[0] || '';

      if (isFirstDay) {
        title = `Day 1 - Arrival`;
        description = `Arrival in ${query.destination.country}. Check-in and orientation.`;
      } else if (isLastDay) {
        title = `Day ${i + 1} - Departure`;
        description = `Check-out and departure from ${query.destination.country}.`;
      } else {
        // Distribute cities across days
        const cityIndex = Math.floor((i - 1) / Math.max(1, Math.floor((tripDuration.days - 2) / query.destination.cities.length)));
        defaultCity = query.destination.cities[cityIndex] || defaultCity;
        title = `Day ${i + 1} - ${defaultCity}`;
        description = `Explore ${defaultCity} and its attractions.`;
      }

      const newDay: ItineraryDay = {
        id: `day_${Date.now()}_${i}`,
        dayNumber: i + 1,
        title,
        city: defaultCity,
        description,
        date: currentDate.toISOString().split('T')[0],
        activities: [],
        transport: [],
        accommodations: [],
        meals: {
          breakfast: !isFirstDay, // No breakfast on arrival day
          lunch: false,
          dinner: false
        },
        totalCost: 0
      };
      
      generatedDays.push(newDay);
    }

    setDays(generatedDays);
  }, []);

  const generateDaysFromCityAllocations = useCallback((query: Query, allocations: any[]) => {
    if (!allocations || allocations.length === 0) return;

    const startDate = new Date(query.travelDates.from);
    const generatedDays: ItineraryDay[] = [];
    let currentDayNumber = 1;
    
    // Calculate total nights and add 1 for departure day
    const totalNights = allocations.reduce((sum, a) => sum + a.nights, 0);
    const totalDays = totalNights + 1;

    // Generate days based on city allocations
    allocations.forEach((allocation, allocationIndex) => {
      if (allocation.nights > 0 && allocation.city) {
        for (let i = 0; i < allocation.nights; i++) {
          const currentDate = new Date(startDate);
          currentDate.setDate(startDate.getDate() + currentDayNumber - 1);
          
          const isFirstDayInCity = i === 0;
          const isLastDayInCity = i === allocation.nights - 1;
          const isFirstDayOverall = currentDayNumber === 1;
          
          let title = `Day ${currentDayNumber}`;
          let description = '';

          if (isFirstDayOverall) {
            title = `Day ${currentDayNumber} - Arrival in ${allocation.city}`;
            description = `Arrival in ${allocation.city}, ${query.destination.country}. Check-in and orientation.`;
          } else if (isFirstDayInCity && allocationIndex > 0) {
            title = `Day ${currentDayNumber} - Transfer to ${allocation.city}`;
            description = `Travel to ${allocation.city}. Check-in and explore.`;
          } else if (isLastDayInCity && allocationIndex < allocations.length - 1) {
            title = `Day ${currentDayNumber} - Last day in ${allocation.city}`;
            description = `Final exploration of ${allocation.city} before moving to next destination.`;
          } else {
            title = `Day ${currentDayNumber} - Explore ${allocation.city}`;
            description = `Full day exploring ${allocation.city} and its attractions.`;
          }

          const newDay: ItineraryDay = {
            id: `day_${Date.now()}_${currentDayNumber}`,
            dayNumber: currentDayNumber,
            title,
            city: allocation.city,
            description,
            date: currentDate.toISOString().split('T')[0],
            activities: [],
            transport: [],
            accommodations: [],
            meals: {
              breakfast: !isFirstDayOverall, // No breakfast on arrival day
              lunch: false,
              dinner: false
            },
            totalCost: 0
          };
          
          generatedDays.push(newDay);
          currentDayNumber++;
        }
      }
    });

    // Add the departure day in the arrival city
    if (allocations.length > 0) {
      const arrivalCity = allocations[0].city; // First city is the arrival city
      const departureDate = new Date(startDate);
      departureDate.setDate(startDate.getDate() + totalNights); // Last day
      
      const departureDay: ItineraryDay = {
        id: `day_${Date.now()}_${totalDays}`,
        dayNumber: totalDays,
        title: `Day ${totalDays} - Departure from ${arrivalCity}`,
        city: arrivalCity,
        description: `Check-out and departure from ${arrivalCity}. End of trip.`,
        date: departureDate.toISOString().split('T')[0],
        activities: [],
        transport: [],
        accommodations: [],
        meals: {
          breakfast: true,
          lunch: false, // Usually no lunch on departure day
          dinner: false // No dinner on departure day
        },
        totalCost: 0
      };
      
      generatedDays.push(departureDay);
    }

    setDays(generatedDays);
  }, []);

  const updateDay = useCallback((dayId: string, updates: Partial<ItineraryDay>) => {
    setDays(prev => {
      const updatedDays = prev.map(day => 
        day.id === dayId 
          ? { ...day, ...updates }
          : day
      );
      
      // No auto-save - data will only be saved on manual save
      return updatedDays;
    });
  }, []);

  const removeDay = useCallback((dayId: string) => {
    setDays(prev => {
      const filtered = prev.filter(day => day.id !== dayId);
      const updatedDays = filtered.map((day, index) => ({
        ...day,
        dayNumber: index + 1,
        title: day.title.includes('Day ') ? `Day ${index + 1}` : day.title
      }));
      
      // No auto-save - data will only be saved on manual save
      return updatedDays;
    });
  }, []);

  const reorderDay = useCallback((dayId: string, direction: 'up' | 'down') => {
    setDays(prev => {
      const currentIndex = prev.findIndex(day => day.id === dayId);
      if (currentIndex === -1) return prev;
      
      const newIndex = direction === 'up' ? currentIndex - 1 : currentIndex + 1;
      if (newIndex < 0 || newIndex >= prev.length) return prev;
      
      const reorderedDays = [...prev];
      const [movedDay] = reorderedDays.splice(currentIndex, 1);
      reorderedDays.splice(newIndex, 0, movedDay);
      
      // Update day numbers after reordering
      const renumberedDays = reorderedDays.map((day, index) => ({
        ...day,
        dayNumber: index + 1,
        title: day.title.includes('Day ') ? `Day ${index + 1}` : day.title
      }));
      
      return renumberedDays;
    });
  }, []);

  const addHotelToDay = useCallback((dayId: string, hotel: any, price?: number) => {
    const finalPrice = price || hotel.minRate || 100;
    
    const accommodationData = {
      id: hotel.id?.toString() || `hotel_${Date.now()}`,
      name: hotel.name,
      type: 'hotel',
      price: finalPrice,
      hotel: hotel.name,
      roomType: hotel.roomTypes?.[0]?.name || 'Standard Room'
    };

    const day = days.find(d => d.id === dayId);
    const activitiesCost = day?.activities.reduce((sum, a) => sum + a.cost, 0) || 0;
    const transportCost = day?.transport?.reduce((sum, t) => sum + t.price, 0) || 0;
    const accommodationsCost = day?.accommodations?.reduce((sum, acc) => sum + acc.price, 0) || 0;

    updateDay(dayId, {
      accommodation: accommodationData,
      totalCost: activitiesCost + transportCost + accommodationsCost + finalPrice
    });
  }, [days, updateDay]);

  const addTransportToDay = useCallback((dayId: string, transport: any, price?: number) => {
    const finalPrice = price || transport.price || 50;
    
    // Enhanced transport activity data
    const transportActivity = {
      id: transport.id?.toString() || `transport_${Date.now()}`,
      name: transport.name,
      description: transport.description || `Transport from ${transport.from} to ${transport.to}`,
      duration: transport.duration || '1 hour',
      cost: finalPrice,
      type: 'transport' as const,
      
      // Transport specific data
      from: transport.from,
      to: transport.to,
      transportType: transport.transportType || transport.vehicleType,
      vehicleType: transport.vehicleType,
      seatingCapacity: transport.seatingCapacity,
      vehicleCount: transport.vehicleCount,
      pickupLocation: transport.pickupLocation,
      dropoffLocation: transport.dropoffLocation,
      pickupTime: transport.pickupTime,
      dropTime: transport.dropTime,
      routeCode: transport.routeCode,
      
      // Data source tracking
      dataSource: 'transport',
      originalData: transport,
      
      // Pricing breakdown
      priceBreakdown: {
        basePrice: finalPrice,
        finalPrice: finalPrice
      }
    };

    const day = days.find(d => d.id === dayId);
    const existingActivitiesCost = day?.activities.reduce((sum, a) => sum + a.cost, 0) || 0;
    const accommodationCost = day?.accommodation?.price || 0;
    const accommodationsCost = day?.accommodations?.reduce((sum, acc) => sum + acc.price, 0) || 0;
    const existingTransportCost = day?.transport?.reduce((sum, t) => sum + t.price, 0) || 0;

    // Add to both activities (for unified tracking) and transport (for legacy compatibility)
    const updatedActivities = [...(day?.activities || []), transportActivity];
    
    updateDay(dayId, {
      activities: updatedActivities,
      transport: day?.transport ? [...day.transport, {
        id: transportActivity.id,
        name: transportActivity.name,
        from: transport.from,
        to: transport.to,
        price: finalPrice,
        type: transport.transportType || transport.vehicleType
      }] : [{
        id: transportActivity.id,
        name: transportActivity.name,
        from: transport.from,
        to: transport.to,
        price: finalPrice,
        type: transport.transportType || transport.vehicleType
      }],
      totalCost: existingActivitiesCost + accommodationCost + accommodationsCost + existingTransportCost + finalPrice
    });
  }, [days, updateDay]);

  const addSightseeingToDay = useCallback((dayId: string, activity: any, price?: number) => {
    const day = days.find(d => d.id === dayId);
    if (!day) return;

    const finalPrice = price || (typeof activity.price === 'object' ? activity.price.adult || 25 : activity.price || 25);

    // Enhanced activity data preservation
    const newActivity = {
      id: activity.id?.toString() || `activity_${Date.now()}`,
      name: activity.name,
      description: activity.description || '',
      duration: activity.duration || '2 hours',
      cost: finalPrice,
      type: 'sightseeing' as const,
      
      // Enhanced sightseeing data
      category: activity.category || activity.data?.category,
      effectivePax: activity.effectivePax || activity.data?.effectivePax,
      startTime: activity.startTime,
      endTime: activity.endTime,
      location: activity.location || activity.city,
      
      // Transport configuration from sightseeing
      transportType: activity.data?.transportType || activity.transportType || activity.pricingSelection?.transferOption?.type,
      transportLabel: activity.data?.transportLabel || activity.transportLabel || activity.pricingSelection?.transferOption?.type,
      vehicleType: activity.pricingSelection?.transferOption?.vehicleType || activity.vehicleType,
      priceUnit: activity.pricingSelection?.transferOption?.priceUnit || activity.priceUnit,
      pickupLocation: activity.pickupLocation,
      dropoffLocation: activity.dropoffLocation,
      seatingCapacity: activity.seatingCapacity,
      
      // Sightseeing selections and options
      selectedOptions: activity.selectedOptions || activity.data?.selectedOptions || [],
      packageOptions: activity.packageOptions || activity.pricingSelection?.packageOptions || [],
      pricingOptions: activity.pricingOptions || activity.pricingSelection?.pricingOptions || [],
      transferOptions: activity.transferOptions || activity.pricingSelection?.transferOptions || [],
      
      // Data source tracking
      dataSource: 'sightseeing',
      originalData: activity.data || activity.pricingSelection,
      
      // Pricing breakdown
      priceBreakdown: {
        basePrice: finalPrice,
        finalPrice: finalPrice
      }
    };

    const updatedActivities = [...day.activities, newActivity];
    const totalActivityCost = updatedActivities.reduce((sum, a) => sum + a.cost, 0);
    const accommodationCost = day.accommodation?.price || 0;
    const accommodationsCost = day.accommodations?.reduce((sum, acc) => sum + acc.price, 0) || 0;
    const transportCost = day.transport?.reduce((sum, t) => sum + t.price, 0) || 0;

    updateDay(dayId, {
      activities: updatedActivities,
      totalCost: totalActivityCost + accommodationCost + accommodationsCost + transportCost
    });
  }, [days, updateDay]);

  const saveDraft = useCallback(async (targetDraftType?: string): Promise<string> => {
    if (!queryId) throw new Error('Query ID is required');
    
    setLoading(true);
    try {
      const finalDraftType = targetDraftType || draftType;
      const draftId = `draft_${queryId}`;
      
      // Use enhanced activity data storage
      const { saveActivityDataWithValidation } = await import('@/utils/activityDataUtils');
      saveActivityDataWithValidation(queryId, days);
      
      const draftData = {
        id: draftId,
        queryId,
        days,
        totalCost,
        draftType: finalDraftType,
        savedAt: new Date().toISOString(),
        version: Date.now()
      };
      
      console.log('Manual save draft data with enhanced activities:', draftData);
      
      // Save with type-specific key
      const storageKey = `proposal_draft_${queryId}_${finalDraftType}`;
      localStorage.setItem(storageKey, JSON.stringify(draftData));
      
      // Also save with legacy key for compatibility
      localStorage.setItem(`proposal_draft_${queryId}`, JSON.stringify(draftData));
      
      // Save accommodation data separately
      const allAccommodations: AccommodationOption[] = days.flatMap(day => 
        (day.accommodations || []).map(acc => ({
          id: acc.id || `acc_${Date.now()}`,
          name: acc.name || acc.hotel || 'Accommodation',
          type: (acc.type || 'hotel') as 'hotel' | 'resort' | 'guesthouse' | 'apartment' | 'villa' | 'hostel',
          city: day.city || '',
          checkIn: day.date,
          checkOut: day.date,
          nights: 1,
          roomType: acc.roomType || 'Standard Room',
          starRating: 3,
          pricePerNight: acc.price || 0,
          totalPrice: acc.price || 0,
          amenities: [],
          description: '',
          address: '',
          phone: '',
          email: '',
          dayIds: [day.id],
          option: 1
        }))
      );
      
      if (allAccommodations.length > 0) {
        saveAccommodationData(queryId, allAccommodations, days);
      }
      
      return draftId;
    } finally {
      setLoading(false);
    }
  }, [queryId, days, totalCost, draftType]);

  const generateProposal = useCallback(async () => {
    if (!queryId) throw new Error('Query ID is required');
    
    setLoading(true);
    try {
      // Convert days to proposal modules
      const modules = days.map(day => ({
        id: day.id,
        type: 'transport' as const,
        name: day.title,
        category: 'itinerary',
        data: {
          dayNumber: day.dayNumber,
          city: day.city,
          description: day.description,
          date: day.date,
          accommodation: day.accommodation,
          accommodations: day.accommodations,
          transport: day.transport,
          activities: day.activities,
          meals: day.meals
        },
        pricing: {
          basePrice: day.totalCost,
          finalPrice: day.totalCost,
          currency: 'USD'
        },
        status: 'active' as const,
        metadata: {
          supplier: 'Internal',
          confirmationRequired: false,
          tags: ['day-by-day', day.city.toLowerCase()]
        }
      }));

      const query = ProposalService.getQueryById(queryId);
      if (!query) throw new Error('Query not found');

      const proposalData = {
        queryId,
        query,
        modules,
        totals: {
          subtotal: totalCost,
          discountAmount: 0,
          total: totalCost,
          moduleCount: modules.length
        },
        metadata: {
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          status: 'draft' as const,
          version: 1
        }
      };

      const proposalId = ProposalService.saveProposal(proposalData);
      
      // Keep draft after successful proposal creation (don't clear)
      
      return proposalId;
    } finally {
      setLoading(false);
    }
  }, [queryId, days, totalCost]);

  const saveAccommodations = useCallback((accommodations: AccommodationOption[]) => {
    if (!queryId) return;
    
    console.log('Saving accommodations from accommodation planning:', accommodations);
    
    // Update days with new accommodations
    const updatedDays = days.map(day => {
      const dayAccommodations = accommodations.filter(acc => 
        acc.dayIds?.includes(day.id) || 
        acc.city === day.city ||
        (acc.checkIn <= day.date && acc.checkOut >= day.date)
      );
      
      return {
        ...day,
        accommodations: dayAccommodations.map(acc => ({
          id: acc.id,
          name: acc.name,
          type: acc.type,
          price: acc.totalPrice,
          hotel: acc.name,
          roomType: acc.roomType
        }))
      };
    });
    
    setDays(updatedDays);
    
    // Save to storage
    saveAccommodationData(queryId, accommodations, updatedDays);
  }, [queryId, days]);

  return {
    days,
    totalCost,
    loading,
    selectedDayId,
    setSelectedDayId,
    addDay,
    addMultipleDays,
    updateDay,
    removeDay,
    reorderDay,
    autoGenerateDaysFromQuery,
    generateDaysFromCityAllocations,
    addHotelToDay,
    addTransportToDay,
    addSightseeingToDay,
    saveDraft,
    generateProposal,
    saveAccommodations,
    loadSpecificDraft
  };
};
