
import {
  Home,
  MessageSquare,
  CheckCircle,
  Calendar,
  Briefcase,
  Building,
  Car,
  Utensils,
  Globe,
  MapPin,
  Landmark,
  Mountain,
  Package,
  UserCheck,
  Users,
  Settings,
  Palette,
  Bell,
  Languages,
  Shield,
  DollarSign,
  BookTemplate,
  LucideIcon
} from 'lucide-react';

const iconMap: { [key: string]: LucideIcon } = {
  'Dashboard': Home,
  'Enquiry Management': MessageSquare,
  'Follow Ups': CheckCircle,
  'Bookings': Calendar,
  'AI Itinerary Builder': Briefcase,
  'Inventory': Package,
  'Templates': BookTemplate,
  'Hotels': Building,
  'Transport': Car,
  'Restaurants': Utensils,
  'Countries': Globe,
  'Cities': MapPin,
  'Visa': Landmark,
  'Sightseeing': Mountain,
  'Packages': Package,
  'Management': Users,
  'Agents': UserCheck,
  'Staff': Users,
  'Settings': Settings,
  'General': Settings,
  'Account': Users,
  'Appearance': Palette,
  'Notifications': Bell,
  'Languages': Globe,
  'Translation Tool': Languages,
  'Currency Converter': DollarSign,
  'API': Settings,
  'Pricing': DollarSign,
  'Access Control': Shield,
  'Agent Management': Users
};

export default iconMap;
