-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action text NOT NULL,
  entity_type text,
  entity_id uuid,
  details jsonb DEFAULT '{}'::jsonb,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.agent_active_sessions (
  agent_id uuid NOT NULL,
  agent_name text NOT NULL,
  login_time timestamp with time zone NOT NULL,
  last_activity timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = 'active'::text),
  login_record_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_active_sessions_pkey PRIMARY KEY (agent_id),
  CONSTRAINT fk_agent_login_record FOREIGN KEY (login_record_id) REFERENCES public.agent_login_records(id)
);
CREATE TABLE public.agent_credentials (
  agent_id uuid NOT NULL,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  is_temporary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_credentials_pkey PRIMARY KEY (agent_id)
);
CREATE TABLE public.agent_login_records (
  id text NOT NULL,
  agent_id uuid NOT NULL,
  agent_name text NOT NULL,
  login_time timestamp with time zone NOT NULL,
  logout_time timestamp with time zone,
  duration_minutes integer,
  status text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'logged-out'::text])),
  ip_address text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_login_records_pkey PRIMARY KEY (id)
);
CREATE TABLE public.agent_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  preferences jsonb DEFAULT '{}'::jsonb,
  notification_settings jsonb DEFAULT '{"sms": false, "push": true, "email": true}'::jsonb,
  security_settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_settings_pkey PRIMARY KEY (id),
  CONSTRAINT agent_settings_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id)
);
CREATE TABLE public.agent_staff_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  staff_id uuid NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  notes text,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  assigned_by uuid,
  CONSTRAINT agent_staff_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT agent_staff_assignments_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id)
);
CREATE TABLE public.agent_tax_info (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid,
  tax_country text,
  tax_type text,
  tax_number text,
  pan_number text,
  gst_number text,
  vat_number text,
  tax_certificate_url text,
  tax_registered boolean DEFAULT false,
  tax_verified boolean DEFAULT false,
  tax_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT agent_tax_info_pkey PRIMARY KEY (id),
  CONSTRAINT agent_tax_info_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id)
);
CREATE TABLE public.agents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  agency_name text,
  agency_code text,
  license_number text,
  iata_number text,
  business_address text,
  business_phone text,
  specializations ARRAY,
  commission_structure jsonb DEFAULT '{"type": "percentage", "value": 10}'::jsonb,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text DEFAULT ''::text UNIQUE,
  email text,
  country text,
  city text,
  business_type text,
  commission_type text,
  commission_value text,
  profile_image text,
  source_type text,
  source_details text,
  created_by uuid,
  created_by_staff text,
  website text,
  alternate_email text,
  mobile_numbers ARRAY,
  documents ARRAY,
  assigned_staff ARRAY DEFAULT '{}'::uuid[],
  suspension_reason text,
  suspended_at timestamp with time zone,
  suspended_by uuid,
  CONSTRAINT agents_pkey PRIMARY KEY (id),
  CONSTRAINT agents_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.app_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text NOT NULL,
  setting_key text NOT NULL,
  setting_value text,
  setting_json jsonb,
  description text,
  data_type text DEFAULT 'text'::text,
  is_required boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT app_settings_pkey PRIMARY KEY (id),
  CONSTRAINT app_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.assignment_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  enquiry_id uuid NOT NULL,
  staff_id uuid NOT NULL,
  assigned_by uuid,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  reason text,
  rule_applied text,
  is_auto_assigned boolean DEFAULT false,
  CONSTRAINT assignment_history_pkey PRIMARY KEY (id),
  CONSTRAINT assignment_history_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES public.enquiries(id),
  CONSTRAINT assignment_history_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.profiles(id),
  CONSTRAINT assignment_history_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.assignment_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  rule_type text NOT NULL,
  priority integer NOT NULL DEFAULT 1,
  enabled boolean DEFAULT true,
  conditions jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assignment_rules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  region text NOT NULL,
  has_airport boolean DEFAULT false,
  is_popular boolean DEFAULT false,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'disabled'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  country_id uuid NOT NULL,
  CONSTRAINT cities_pkey PRIMARY KEY (id),
  CONSTRAINT cities_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id)
);
CREATE TABLE public.countries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  code text NOT NULL UNIQUE,
  region text NOT NULL,
  continent text NOT NULL,
  currency text NOT NULL,
  currency_symbol text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  flag_url text,
  is_popular boolean DEFAULT false,
  visa_required boolean DEFAULT false,
  languages jsonb DEFAULT '[]'::jsonb,
  pricing_currency_override boolean DEFAULT false,
  pricing_currency text,
  pricing_currency_symbol text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT countries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.currency_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  base_currency text NOT NULL DEFAULT 'USD'::text,
  target_currency text NOT NULL,
  rate numeric NOT NULL,
  last_updated timestamp with time zone NOT NULL DEFAULT now(),
  source text DEFAULT 'manual'::text,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT currency_rates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dashboard_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message text NOT NULL,
  details text,
  type text NOT NULL DEFAULT 'info'::text CHECK (type = ANY (ARRAY['info'::text, 'warning'::text, 'error'::text, 'success'::text])),
  is_read boolean DEFAULT false,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT dashboard_alerts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dashboard_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text])),
  due_date timestamp with time zone,
  assigned_to uuid,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT dashboard_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.debug_log (
  id bigint NOT NULL DEFAULT nextval('debug_log_id_seq'::regclass),
  message text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT debug_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.departments (
  id text NOT NULL,
  name text NOT NULL,
  code text NOT NULL UNIQUE,
  description text,
  staff_count integer DEFAULT 0,
  features jsonb NOT NULL DEFAULT '[]'::jsonb,
  workflow jsonb NOT NULL DEFAULT '{}'::jsonb,
  permissions jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.enquiries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  enquiry_id text NOT NULL UNIQUE,
  agent_id uuid,
  assigned_to uuid,
  created_by uuid,
  country_code text NOT NULL,
  country_name text NOT NULL,
  cities jsonb NOT NULL DEFAULT '[]'::jsonb,
  travel_from date NOT NULL,
  travel_to date NOT NULL,
  is_date_estimated boolean DEFAULT false,
  nights integer NOT NULL,
  days integer NOT NULL,
  adults integer NOT NULL DEFAULT 1,
  children integer NOT NULL DEFAULT 0,
  infants integer NOT NULL DEFAULT 0,
  budget_min numeric,
  budget_max numeric,
  budget_currency text DEFAULT 'USD'::text,
  package_type text NOT NULL,
  hotel_rooms integer,
  hotel_category text,
  sightseeing boolean DEFAULT true,
  transfers text DEFAULT 'private'::text,
  meal_plan text DEFAULT 'breakfast'::text,
  special_requests jsonb DEFAULT '[]'::jsonb,
  notes text,
  status text NOT NULL DEFAULT 'new'::text,
  priority text DEFAULT 'normal'::text,
  communication_preference text DEFAULT 'email'::text,
  city_allocations jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT enquiries_pkey PRIMARY KEY (id),
  CONSTRAINT enquiries_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id),
  CONSTRAINT enquiries_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id),
  CONSTRAINT enquiries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.enquiry_workflow_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  enquiry_id uuid NOT NULL,
  event_type text NOT NULL,
  user_id uuid,
  user_name text,
  user_role text,
  details text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT enquiry_workflow_events_pkey PRIMARY KEY (id),
  CONSTRAINT enquiry_workflow_events_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES public.enquiries(id),
  CONSTRAINT enquiry_workflow_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.follow_ups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  type text NOT NULL DEFAULT 'general'::text CHECK (type = ANY (ARRAY['general'::text, 'call'::text, 'email'::text, 'meeting'::text, 'quote'::text, 'booking'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  due_date timestamp with time zone NOT NULL,
  contact_name text,
  contact_email text,
  contact_phone text,
  related_enquiry_id uuid,
  related_booking_id uuid,
  assigned_to uuid,
  notes text,
  completed_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT follow_ups_pkey PRIMARY KEY (id),
  CONSTRAINT follow_ups_related_enquiry_id_fkey FOREIGN KEY (related_enquiry_id) REFERENCES public.sales_enquiries(id),
  CONSTRAINT follow_ups_related_booking_id_fkey FOREIGN KEY (related_booking_id) REFERENCES public.sales_bookings(id),
  CONSTRAINT follow_ups_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.hotel_room_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  external_id integer,
  hotel_id uuid NOT NULL,
  name text NOT NULL,
  capacity jsonb NOT NULL,
  configuration text,
  meal_plan text,
  valid_from date,
  valid_to date,
  adult_price numeric NOT NULL DEFAULT 0,
  child_price numeric NOT NULL DEFAULT 0,
  extra_bed_price numeric NOT NULL DEFAULT 0,
  description text,
  amenities jsonb DEFAULT '[]'::jsonb,
  images jsonb DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hotel_room_types_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_room_types_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES public.hotels(id)
);
CREATE TABLE public.hotels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  external_id integer,
  name text NOT NULL,
  star_rating integer CHECK (star_rating >= 1 AND star_rating <= 5),
  category text,
  country text NOT NULL,
  city text NOT NULL,
  location text,
  address jsonb,
  latitude numeric,
  longitude numeric,
  google_map_link text,
  check_in_time text,
  check_out_time text,
  description text,
  amenities jsonb DEFAULT '[]'::jsonb,
  images jsonb DEFAULT '[]'::jsonb,
  contact_info jsonb,
  facilities jsonb DEFAULT '[]'::jsonb,
  policies jsonb,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_updated timestamp with time zone DEFAULT now(),
  currency text,
  currency_symbol text,
  CONSTRAINT hotels_pkey PRIMARY KEY (id)
);
CREATE TABLE public.intermediate_stops (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_id uuid NOT NULL,
  stop_order integer NOT NULL,
  location_code character varying NOT NULL,
  full_name character varying NOT NULL,
  coordinates jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  transfer_method_notes text,
  luggage_capacity jsonb,
  CONSTRAINT intermediate_stops_pkey PRIMARY KEY (id),
  CONSTRAINT intermediate_stops_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.transport_routes(id)
);
CREATE TABLE public.itinerary_days (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid NOT NULL,
  day_number integer NOT NULL CHECK (day_number > 0),
  title text NOT NULL,
  location text NOT NULL,
  activities jsonb DEFAULT '[]'::jsonb,
  accommodation_name text,
  accommodation_type text,
  accommodation_category text,
  breakfast boolean DEFAULT false,
  lunch boolean DEFAULT false,
  dinner boolean DEFAULT false,
  accommodation_cost numeric DEFAULT 0,
  sightseeing_cost numeric DEFAULT 0,
  meals_cost numeric DEFAULT 0,
  transfer_cost numeric DEFAULT 0,
  other_cost numeric DEFAULT 0,
  total_day_cost numeric DEFAULT ((((accommodation_cost + sightseeing_cost) + meals_cost) + transfer_cost) + other_cost),
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT itinerary_days_pkey PRIMARY KEY (id),
  CONSTRAINT itinerary_days_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.proposals(id)
);
CREATE TABLE public.location_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  full_name text NOT NULL,
  category text NOT NULL,
  country text NOT NULL,
  city text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text,
  notes text,
  latitude double precision,
  longitude double precision,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT location_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.login_activity (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  login_time timestamp with time zone NOT NULL DEFAULT now(),
  ip_address text,
  user_agent text,
  success boolean DEFAULT true,
  CONSTRAINT login_activity_pkey PRIMARY KEY (id),
  CONSTRAINT login_activity_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.markup_slabs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  config_id uuid NOT NULL,
  min_amount numeric NOT NULL,
  max_amount numeric NOT NULL,
  additional_percentage numeric NOT NULL,
  fixed_amount numeric DEFAULT 0,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT markup_slabs_pkey PRIMARY KEY (id),
  CONSTRAINT markup_slabs_config_id_fkey FOREIGN KEY (config_id) REFERENCES public.pricing_configurations(id)
);
CREATE TABLE public.pricing_configurations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  country_code text NOT NULL UNIQUE,
  country_name text NOT NULL,
  currency text NOT NULL,
  currency_symbol text NOT NULL,
  tax_type text NOT NULL DEFAULT 'NONE'::text CHECK (tax_type = ANY (ARRAY['GST'::text, 'VAT'::text, 'SALES_TAX'::text, 'NONE'::text])),
  tax_enabled boolean NOT NULL DEFAULT true,
  tds_enabled boolean NOT NULL DEFAULT false,
  tds_rate numeric DEFAULT 0,
  tds_threshold numeric DEFAULT 0,
  tds_exemption_limit numeric DEFAULT 0,
  tds_company_registration text,
  base_markup_percentage numeric NOT NULL DEFAULT 10,
  slab_markup_enabled boolean NOT NULL DEFAULT false,
  tier_multiplier numeric DEFAULT 1.0,
  seasonal_adjustment numeric DEFAULT 0,
  minimum_markup numeric,
  maximum_markup numeric,
  is_active boolean NOT NULL DEFAULT true,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT pricing_configurations_pkey PRIMARY KEY (id),
  CONSTRAINT pricing_configurations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT pricing_configurations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  name text,
  email text,
  role text DEFAULT ''::text,
  department text,
  phone text,
  status text DEFAULT ''::text,
  position text,
  employee_id text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  company_name text,
  avatar text,
  preferred_language text,
  country text,
  city text,
  must_change_password boolean DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.proposal_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  external_id text,
  name text NOT NULL,
  description text,
  destination jsonb NOT NULL,
  duration jsonb NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['Budget'::text, 'Standard'::text, 'Premium'::text, 'Luxury'::text])),
  day_plan jsonb DEFAULT '[]'::jsonb,
  pricing_matrix jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT proposal_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.proposals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id text NOT NULL UNIQUE,
  enquiry_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  cost_per_person numeric NOT NULL,
  total_cost numeric NOT NULL,
  final_price numeric NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  status text NOT NULL DEFAULT 'draft'::text,
  inclusions jsonb DEFAULT '[]'::jsonb,
  exclusions jsonb DEFAULT '[]'::jsonb,
  terms text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  sent_at timestamp with time zone,
  accepted_at timestamp with time zone,
  rejected_at timestamp with time zone,
  CONSTRAINT proposals_pkey PRIMARY KEY (id),
  CONSTRAINT proposals_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES public.enquiries(id),
  CONSTRAINT proposals_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.restaurants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  external_id text,
  name text NOT NULL,
  location text,
  cuisine text,
  address text NOT NULL,
  city text NOT NULL,
  country text NOT NULL,
  area text,
  price_range text,
  price_category text NOT NULL CHECK (price_category = ANY (ARRAY['$'::text, '$$'::text, '$$$'::text, '$$$$'::text])),
  average_price numeric,
  average_cost numeric NOT NULL,
  rating numeric CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  review_count integer DEFAULT 0,
  opening_hours text,
  opening_time text,
  closing_time text,
  contact text,
  description text,
  images jsonb DEFAULT '[]'::jsonb,
  image_url text,
  features jsonb NOT NULL,
  meal_types jsonb NOT NULL,
  dietary_options jsonb NOT NULL,
  cuisine_types jsonb DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  is_preferred boolean DEFAULT false,
  currency_symbol text,
  currency_code text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT restaurants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sales_bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id text NOT NULL UNIQUE,
  enquiry_id uuid,
  client_name text NOT NULL,
  contact_person text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  destination text NOT NULL,
  travelers integer NOT NULL DEFAULT 1,
  total_amount numeric NOT NULL DEFAULT 0,
  paid_amount numeric NOT NULL DEFAULT 0,
  balance_amount numeric NOT NULL DEFAULT 0,
  currency text DEFAULT 'INR'::text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text, 'completed'::text])),
  booking_date timestamp with time zone NOT NULL DEFAULT now(),
  travel_date timestamp with time zone,
  duration text,
  commission numeric DEFAULT 0,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'advance'::text, 'partial'::text, 'paid'::text])),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sales_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT sales_bookings_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES public.sales_enquiries(id),
  CONSTRAINT sales_bookings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.sales_enquiries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  enquiry_id text NOT NULL UNIQUE,
  client_name text NOT NULL,
  contact_person text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  destination text NOT NULL,
  travelers integer NOT NULL DEFAULT 1,
  budget numeric,
  budget_currency text DEFAULT 'INR'::text,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'hot'::text, 'followup'::text, 'converted'::text, 'lost'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  date_received timestamp with time zone NOT NULL DEFAULT now(),
  follow_up_date timestamp with time zone,
  duration text,
  requirements text,
  assigned_to uuid,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sales_enquiries_pkey PRIMARY KEY (id),
  CONSTRAINT sales_enquiries_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.sales_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id text NOT NULL UNIQUE,
  company_name text NOT NULL,
  contact_person text NOT NULL,
  email text NOT NULL,
  phone text,
  source text,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'contacted'::text, 'qualified'::text, 'proposal'::text, 'negotiation'::text, 'closed_won'::text, 'closed_lost'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  estimated_value numeric,
  estimated_currency text DEFAULT 'INR'::text,
  next_action text,
  next_action_date timestamp with time zone,
  notes text,
  assigned_to uuid,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sales_leads_pkey PRIMARY KEY (id),
  CONSTRAINT sales_leads_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.sales_quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id text NOT NULL UNIQUE,
  enquiry_id uuid,
  client_name text NOT NULL,
  destination text NOT NULL,
  total_amount numeric NOT NULL DEFAULT 0,
  currency text DEFAULT 'INR'::text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'viewed'::text, 'accepted'::text, 'rejected'::text, 'expired'::text])),
  valid_until timestamp with time zone,
  quote_data jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sales_quotes_pkey PRIMARY KEY (id),
  CONSTRAINT sales_quotes_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES public.sales_enquiries(id),
  CONSTRAINT sales_quotes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.sightseeing (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  external_id integer,
  name text NOT NULL,
  description text,
  country text NOT NULL,
  city text NOT NULL,
  category text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  duration text,
  timing text,
  difficulty_level text,
  allowed_age_group text,
  address text,
  google_map_link text,
  price jsonb,
  is_free boolean DEFAULT false,
  sic_available boolean DEFAULT false,
  sic_pricing jsonb,
  requires_mandatory_transfer boolean DEFAULT false,
  transfer_mandatory boolean DEFAULT false,
  transfer_options jsonb DEFAULT '[]'::jsonb,
  pricing_options jsonb DEFAULT '[]'::jsonb,
  package_options jsonb DEFAULT '[]'::jsonb,
  group_size_options jsonb DEFAULT '[]'::jsonb,
  policies jsonb,
  validity_period jsonb,
  images jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_updated timestamp with time zone DEFAULT now(),
  latitude double precision,
  longitude double precision,
  activities ARRAY DEFAULT '{}'::text[],
  season text,
  days_of_week ARRAY DEFAULT '{}'::text[],
  pickup_time text,
  pricing_currency text,
  pricing_currency_symbol text,
  CONSTRAINT sightseeing_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sightseeing_options (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_id uuid NOT NULL,
  location character varying NOT NULL,
  description text,
  adult_price numeric NOT NULL,
  child_price numeric NOT NULL,
  additional_charges numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sightseeing_options_pkey PRIMARY KEY (id),
  CONSTRAINT sightseeing_options_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.transport_routes(id)
);
CREATE TABLE public.staff (
  id uuid NOT NULL,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  phone text,
  department text,
  role text NOT NULL,
  status text DEFAULT 'active'::text,
  employee_id text UNIQUE,
  join_date date,
  reporting_manager text,
  date_of_birth date,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  operational_countries ARRAY,
  position text,
  avatar text,
  Documents text,
  CONSTRAINT staff_pkey PRIMARY KEY (id),
  CONSTRAINT staff_id_fkey FOREIGN KEY (id) REFERENCES public.profiles(id)
);
CREATE TABLE public.staff_active_sessions (
  staff_id uuid NOT NULL,
  staff_name text NOT NULL,
  login_time timestamp with time zone NOT NULL,
  last_activity timestamp with time zone NOT NULL,
  status text NOT NULL CHECK (status = 'active'::text),
  login_record_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staff_active_sessions_pkey PRIMARY KEY (staff_id),
  CONSTRAINT fk_login_record FOREIGN KEY (login_record_id) REFERENCES public.staff_login_records(id)
);
CREATE TABLE public.staff_bank_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  staff_id uuid NOT NULL UNIQUE,
  bank_name text NOT NULL,
  account_holder_name text NOT NULL,
  account_number_encrypted text NOT NULL,
  account_number_last4 text NOT NULL,
  country text,
  ifsc_or_swift text,
  branch text,
  verified_status text NOT NULL DEFAULT 'unverified'::text CHECK (verified_status = ANY (ARRAY['unverified'::text, 'pending'::text, 'verified'::text, 'rejected'::text])),
  verified_by uuid,
  verified_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT staff_bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT staff_bank_accounts_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id),
  CONSTRAINT staff_bank_accounts_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.staff_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  staff_id uuid NOT NULL,
  doc_type text NOT NULL,
  file_name text NOT NULL,
  file_ext text,
  mime_type text,
  size_bytes integer,
  storage_path text NOT NULL,
  sha256 text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  verified_by uuid,
  verified_at timestamp without time zone,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT staff_documents_pkey PRIMARY KEY (id),
  CONSTRAINT staff_documents_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id),
  CONSTRAINT staff_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.staff_login_records (
  id text NOT NULL,
  staff_id uuid NOT NULL,
  staff_name text NOT NULL,
  login_time timestamp with time zone NOT NULL,
  logout_time timestamp with time zone,
  duration_minutes integer,
  status text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'logged-out'::text])),
  ip_address text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staff_login_records_pkey PRIMARY KEY (id)
);
CREATE TABLE public.staff_referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  staff_id uuid,
  referral_code text NOT NULL UNIQUE,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT staff_referrals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.staff_sequence (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  staff_id uuid NOT NULL UNIQUE,
  sequence_order integer NOT NULL CHECK (sequence_order > 0),
  auto_assign_enabled boolean DEFAULT true,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staff_sequence_pkey PRIMARY KEY (id),
  CONSTRAINT staff_sequence_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.profiles(id),
  CONSTRAINT staff_sequence_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT staff_sequence_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.staff_workload (
  staff_id uuid NOT NULL,
  active_enquiries integer DEFAULT 0,
  total_enquiries integer DEFAULT 0,
  conversion_rate numeric DEFAULT 0,
  avg_response_time integer DEFAULT 0,
  last_assignment timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staff_workload_pkey PRIMARY KEY (staff_id),
  CONSTRAINT staff_workload_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.tax_exemptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  config_id uuid NOT NULL,
  service_type text NOT NULL,
  reason text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  valid_from date,
  valid_to date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tax_exemptions_pkey PRIMARY KEY (id),
  CONSTRAINT tax_exemptions_config_id_fkey FOREIGN KEY (config_id) REFERENCES public.pricing_configurations(id)
);
CREATE TABLE public.tax_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  config_id uuid NOT NULL,
  service_type text NOT NULL CHECK (service_type = ANY (ARRAY['transport'::text, 'hotel'::text, 'sightseeing'::text, 'restaurant'::text, 'activity'::text, 'all'::text])),
  rate numeric NOT NULL,
  description text NOT NULL,
  is_default boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  valid_from date,
  valid_to date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tax_rates_pkey PRIMARY KEY (id),
  CONSTRAINT tax_rates_config_id_fkey FOREIGN KEY (config_id) REFERENCES public.pricing_configurations(id)
);
CREATE TABLE public.tour_packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  external_id text,
  name text NOT NULL,
  summary text,
  description text,
  min_pax integer NOT NULL,
  max_pax integer,
  days integer NOT NULL,
  nights integer NOT NULL,
  is_fixed_departure boolean DEFAULT false,
  departure_date date,
  return_date date,
  total_seats integer,
  start_city text,
  end_city text,
  destinations jsonb DEFAULT '[]'::jsonb,
  package_type text NOT NULL CHECK (package_type = ANY (ARRAY['domestic'::text, 'international'::text, 'custom'::text, 'inbound'::text])),
  themes jsonb DEFAULT '[]'::jsonb,
  banners jsonb DEFAULT '[]'::jsonb,
  itinerary jsonb DEFAULT '[]'::jsonb,
  base_cost numeric NOT NULL DEFAULT 0,
  markup numeric NOT NULL DEFAULT 0,
  commission numeric,
  final_price numeric NOT NULL DEFAULT 0,
  price_per_person numeric NOT NULL DEFAULT 0,
  currency text NOT NULL,
  inclusions text,
  exclusions text,
  cancellation_policy text,
  payment_policy text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tour_packages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transport_routes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_code character varying NOT NULL,
  route_name character varying NOT NULL,
  country text,
  transfer_type character varying NOT NULL CHECK (transfer_type::text = ANY (ARRAY['One-Way'::character varying, 'Round-Trip'::character varying, 'Multi-Stop'::character varying, 'en route'::character varying]::text[])),
  start_location character varying NOT NULL,
  start_location_full_name character varying,
  start_coordinates jsonb,
  end_location character varying NOT NULL,
  end_location_full_name character varying,
  end_coordinates jsonb,
  distance integer,
  duration character varying,
  notes text,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  enable_sightseeing boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name text NOT NULL DEFAULT ''::text,
  vehicle_types jsonb,
  luggage_capacity jsonb,
  CONSTRAINT transport_routes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transport_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  category text NOT NULL,
  seating_capacity integer DEFAULT 0,
  luggage_capacity integer DEFAULT 0,
  active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by text,
  updated_by text,
  CONSTRAINT transport_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trigger_errors (
  id integer NOT NULL DEFAULT nextval('trigger_errors_id_seq'::regclass),
  trigger_name text,
  user_id uuid,
  err_msg text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trigger_errors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  role text NOT NULL,
  permissions jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.visa (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  country text NOT NULL,
  visa_type text NOT NULL,
  processing_time text,
  validity text,
  price numeric DEFAULT 0,
  is_rush_available boolean DEFAULT false,
  rush_processing_time text,
  rush_price numeric,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'disabled'::text])),
  requirements text,
  documents jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT visa_pkey PRIMARY KEY (id)
);