// Currency mapping for countries
export const countryCurrencyMap: Record<string, { code: string; symbol: string }> = {
  'Thailand': { code: 'THB', symbol: '฿' },
  'UAE': { code: 'AED', symbol: 'د.إ' },
  'Japan': { code: 'JPY', symbol: '¥' },
  'Singapore': { code: 'SGD', symbol: 'S$' },
  'Malaysia': { code: 'MYR', symbol: 'RM' },
  'India': { code: 'INR', symbol: '₹' },
  'Nepal': { code: 'NPR', symbol: 'Rs' },
  'Sri Lanka': { code: 'LKR', symbol: 'Rs' },
  'Maldives': { code: 'MVR', symbol: 'Rf' },
  'Turkey': { code: 'TRY', symbol: '₺' },
  'Egypt': { code: 'EGP', symbol: 'E£' },
  'South Korea': { code: 'KRW', symbol: '₩' },
  'China': { code: 'CNY', symbol: '¥' },
  'Indonesia': { code: 'IDR', symbol: 'Rp' },
  'Philippines': { code: 'PHP', symbol: '₱' },
  'Vietnam': { code: 'VND', symbol: '₫' },
  'Cambodia': { code: 'KHR', symbol: '៛' },
  'Laos': { code: 'LAK', symbol: '₭' },
  'Myanmar': { code: 'MMK', symbol: 'K' },
  'United States': { code: 'USD', symbol: '$' },
  'United Kingdom': { code: 'GBP', symbol: '£' },
  'Australia': { code: 'AUD', symbol: 'A$' },
  'Canada': { code: 'CAD', symbol: 'C$' },
  'New Zealand': { code: 'NZD', symbol: 'NZ$' },
  'South Africa': { code: 'ZAR', symbol: 'R' },
  'Kenya': { code: 'KES', symbol: 'KSh' },
  'Tanzania': { code: 'TZS', symbol: 'TSh' },
  'Morocco': { code: 'MAD', symbol: 'د.م.' },
  'Jordan': { code: 'JOD', symbol: 'د.ا' },
  'Lebanon': { code: 'LBP', symbol: 'ل.ل' },
  'Qatar': { code: 'QAR', symbol: 'ر.ق' },
  'Kuwait': { code: 'KWD', symbol: 'د.ك' },
  'Saudi Arabia': { code: 'SAR', symbol: 'ر.س' },
  'Oman': { code: 'OMR', symbol: 'ر.ع.' },
  'Bahrain': { code: 'BHD', symbol: '.د.ب' },
  'Iran': { code: 'IRR', symbol: '﷼' },
  'Israel': { code: 'ILS', symbol: '₪' },
  'Georgia': { code: 'GEL', symbol: '₾' },
  'Armenia': { code: 'AMD', symbol: '֏' },
  'Azerbaijan': { code: 'AZN', symbol: '₼' },
  'Kazakhstan': { code: 'KZT', symbol: '₸' },
  'Uzbekistan': { code: 'UZS', symbol: 'сўм' },
  'Kyrgyzstan': { code: 'KGS', symbol: 'с' },
  'Tajikistan': { code: 'TJS', symbol: 'смн' },
  'Turkmenistan': { code: 'TMT', symbol: 'T' },
  'Afghanistan': { code: 'AFN', symbol: '؋' },
  'Pakistan': { code: 'PKR', symbol: 'Rs' },
  'Bangladesh': { code: 'BDT', symbol: '৳' },
  'Bhutan': { code: 'BTN', symbol: 'Nu.' },
  'Mongolia': { code: 'MNT', symbol: '₮' },
  'Brazil': { code: 'BRL', symbol: 'R$' },
  'Argentina': { code: 'ARS', symbol: '$' },
  'Chile': { code: 'CLP', symbol: '$' },
  'Peru': { code: 'PEN', symbol: 'S/' },
  'Colombia': { code: 'COP', symbol: '$' },
  'Ecuador': { code: 'USD', symbol: '$' },
  'Bolivia': { code: 'BOB', symbol: 'Bs' },
  'Uruguay': { code: 'UYU', symbol: '$U' },
  'Paraguay': { code: 'PYG', symbol: '₲' },
  'Venezuela': { code: 'VES', symbol: 'Bs.S' },
  'Mexico': { code: 'MXN', symbol: '$' },
  'Guatemala': { code: 'GTQ', symbol: 'Q' },
  'Costa Rica': { code: 'CRC', symbol: '₡' },
  'Panama': { code: 'PAB', symbol: 'B/.' },
  'Nicaragua': { code: 'NIO', symbol: 'C$' },
  'Honduras': { code: 'HNL', symbol: 'L' },
  'El Salvador': { code: 'USD', symbol: '$' },
  'Belize': { code: 'BZD', symbol: 'BZ$' },
  'Jamaica': { code: 'JMD', symbol: 'J$' },
  'Cuba': { code: 'CUP', symbol: '₱' },
  'Dominican Republic': { code: 'DOP', symbol: 'RD$' },
  'Haiti': { code: 'HTG', symbol: 'G' },
  'Puerto Rico': { code: 'USD', symbol: '$' },
  'Barbados': { code: 'BBD', symbol: 'Bds$' },
  'Trinidad and Tobago': { code: 'TTD', symbol: 'TT$' },
  'Bahamas': { code: 'BSD', symbol: 'B$' },
  'Iceland': { code: 'ISK', symbol: 'kr' },
  'Norway': { code: 'NOK', symbol: 'kr' },
  'Sweden': { code: 'SEK', symbol: 'kr' },
  'Denmark': { code: 'DKK', symbol: 'kr' },
  'Finland': { code: 'EUR', symbol: '€' },
  'Estonia': { code: 'EUR', symbol: '€' },
  'Latvia': { code: 'EUR', symbol: '€' },
  'Lithuania': { code: 'EUR', symbol: '€' },
  'Poland': { code: 'PLN', symbol: 'zł' },
  'Czech Republic': { code: 'CZK', symbol: 'Kč' },
  'Slovakia': { code: 'EUR', symbol: '€' },
  'Hungary': { code: 'HUF', symbol: 'Ft' },
  'Slovenia': { code: 'EUR', symbol: '€' },
  'Croatia': { code: 'EUR', symbol: '€' },
  'Bosnia and Herzegovina': { code: 'BAM', symbol: 'KM' },
  'Serbia': { code: 'RSD', symbol: 'дин.' },
  'Montenegro': { code: 'EUR', symbol: '€' },
  'North Macedonia': { code: 'MKD', symbol: 'ден' },
  'Albania': { code: 'ALL', symbol: 'L' },
  'Bulgaria': { code: 'BGN', symbol: 'лв' },
  'Romania': { code: 'RON', symbol: 'lei' },
  'Moldova': { code: 'MDL', symbol: 'L' },
  'Ukraine': { code: 'UAH', symbol: '₴' },
  'Belarus': { code: 'BYN', symbol: 'Br' },
  'Russia': { code: 'RUB', symbol: '₽' },
  'Germany': { code: 'EUR', symbol: '€' },
  'France': { code: 'EUR', symbol: '€' },
  'Italy': { code: 'EUR', symbol: '€' },
  'Spain': { code: 'EUR', symbol: '€' },
  'Portugal': { code: 'EUR', symbol: '€' },
  'Netherlands': { code: 'EUR', symbol: '€' },
  'Belgium': { code: 'EUR', symbol: '€' },
  'Luxembourg': { code: 'EUR', symbol: '€' },
  'Austria': { code: 'EUR', symbol: '€' },
  'Switzerland': { code: 'CHF', symbol: 'CHF' },
  'Liechtenstein': { code: 'CHF', symbol: 'CHF' },
  'Greece': { code: 'EUR', symbol: '€' },
  'Cyprus': { code: 'EUR', symbol: '€' },
  'Malta': { code: 'EUR', symbol: '€' },
  'Ireland': { code: 'EUR', symbol: '€' },
  'Monaco': { code: 'EUR', symbol: '€' },
  'San Marino': { code: 'EUR', symbol: '€' },
  'Vatican City': { code: 'EUR', symbol: '€' },
  'Andorra': { code: 'EUR', symbol: '€' }
};

export const getCurrencyByCountry = (country: string) => {
  return countryCurrencyMap[country] || { code: 'USD', symbol: '$' };
};

export const formatCurrency = (amount: number, country: string, includeCode: boolean = false) => {
  const currency = getCurrencyByCountry(country);
  if (includeCode) {
    return `${currency.symbol}${amount.toFixed(2)} ${currency.code}`;
  }
  return `${currency.symbol}${amount.toFixed(2)}`;
};